### ISSUE TITLE
General : Bootstrap width of the page should be 1170px as per design

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Studio66#23]
![2016-04-28_1535](https://cloud.githubusercontent.com/assets/13309806/14883814/28533c5e-0d5e-11e6-8378-4533a2382622.png)

**Comment by Santosh-titan** [comment]
In Bootstrap container width is 1140px and padding 15px both sides. You Should calculate it also. This is how bootstrap works.
1140px+15px+15px = 1170px
